### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by AymenOthmani** [Mathew78540/realaion#1]
Hello 
i tired to install this website but he won't work 
http://imgur.com/nu7tAyN

installed all database

**Comment by mathieuletyrant** [comment]
Hi,

For have more details you must set APP_DEBUG to true in your .env file

**Comment by mathieuletyrant** [comment]
When i will have more free time, i will try to update the website and cleanup this.

**Comment by AymenOthmani** [comment]
ok thanks

**Comment by AymenOthmani** [comment]
i think missing sql database.gs i can't find in it, i tried with aion.gs 4.9 sql but i got error
http://i.imgur.com/nhb3LYn.jpg

**Comment by ghost** [comment]
I have this error : 

QueryException in Connection.php line 624:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'aion_gs.ladder_player' doesn't exist (SQL: select \* from `ladder_player` order by `rating` desc limit 5)

The website needs a ladder_player table into gameserver database, but there is no SQL file to update the database.

EDIT : And finally, if we create missing empty tables, here is the result : 
![2016-07-26_23h59_51](https://cloud.githubusercontent.com/assets/20670942/17157038/200ef57c-538d-11e6-9478-161b007fa220.png)

**Comment by mathieuletyrant** [comment]
Now, you must have NodeJS with NPM and after :

``` shell
npm install
npm install -g gulp
gulp script
gulp style
```

**Comment by ghost** [comment]
There are some WARN during instructions : 

```
[root]/var/www/html > npm install
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

[root]/var/www/html > npm install -g gulp
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```

But the theme is still not accessible, I have the same result than my previous screenshot.
