### ISSUE TITLE
same with webshop

### ISSUE THREAD

**Issue by AymenOthmani** [Mathew78540/realaion#12]
i think problems about links need fixes.. 
try with account luffy pw : test
http://74.208.230.63/test/public/shop  :(

**Comment by mathieuletyrant** [comment]
I haven't problems with my configuration ...

**Comment by mathieuletyrant** [comment]
If you use Nginx, look : http://laravel-recipes.com/recipes/26/creating-a-nginx-virtualhost
If you use Apache, look : http://laravel-recipes.com/recipes/25/creating-an-apache-virtualhost

**Comment by AymenOthmani** [comment]
thanks man everything work fine www.fighter-aion.com need only change logo :D 

Great job :+1:

**Comment by mathieuletyrant** [comment]
Ok, so i closed the issue. Good luck !
