### ISSUE TITLE
Request : Add log reader into admin interface

### ISSUE THREAD

**Issue by ghost** [Mathew78540/realaion#14]
Can you add a logreader directly into admin interface instead of downloading log file ?

![2016-07-30_18h23_00](https://cloud.githubusercontent.com/assets/20670942/17271694/bb2e6d88-5682-11e6-99c2-5cd3e8c1ddfe.png)

**Comment by mathieuletyrant** [comment]
Impossible, sometimes files can be very heavy. And if the server try to read that files the Google chrome will crach. So request Reject for now.
