### ISSUE TITLE
Missing functionnality : Edit Shop item 

### ISSUE THREAD

**Issue by ghost** [Mathew78540/realaion#17]
I have created an item into the shop, but I can't edit it from the admin interface.

**Comment by ghost** [comment]
OK I found how I can edit an item, but it is not easy to do.
![2016-08-02_00h58_07](https://cloud.githubusercontent.com/assets/20670942/17311527/5193ec4c-584c-11e6-879d-ef91f551beaf.png)
Can you add a table with all items + filter categories / sub-categories into the Shop nav menu ?

**Comment by mathieuletyrant** [comment]
Duplicate with #20
