### ISSUE TITLE
Request : Remove the cart option for the Webshop

### ISSUE THREAD

**Issue by ghost** [Mathew78540/realaion#19]
Is it possible to add an option for the cart use ? And when player click on Add, there is a confirmation message (it cost 1 point, you have 10 points, you will have 9 after buy, are you sure ?) and if Yes item is directly buy.

**Comment by mathieuletyrant** [comment]
How the use choose a character ?

**Comment by ghost** [comment]
Please select the character ? :) I don't know where, the solution should be the same function that now, but instead of Add you have Buy, when you click on Buy it make the same action than Add to cart and select the character but user doesn't see the cart.

**Comment by ghost** [comment]
You can cancel this request, I will probably need cart so I won't disable this functionnality.
