### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by AymenOthmani** [Mathew78540/realaion#2]
Hey matthew
i just followed your Installation guide to set up website 
- installed website with composer.
- added file .env. 
- added vote / real / email / token to account data.
- also added ladder_player to database .gs.
  but website won't work i don't know form what the issues but i think missing something in database.ws.
  this the error : 
  Trying to get property of non-object (View: C:\xampp\htdocs\master\resources\views_modules\news.blade.php) (View: C:\xampp\htdocs\master\resources\views_modules\news.blade.php)
  
  **http://i.imgur.com/PK25EEa.jpg**

i hope you can help me and thanks.

**Comment by ghost** [comment]
May be this issue should be closed ? Readme has been updated with all necessary instructions to troubleshout these errors.
