### ISSUE TITLE
Missing functionnality : list items shop per categories

### ISSUE THREAD

**Issue by ghost** [Mathew78540/realaion#20]
Can we see somewhere in the admin site the list of all shop items created, their price, categorie, sub categorie, etc ?

**Comment by mathieuletyrant** [comment]
In the nav, you select shop and you can search items in the shop.

**Comment by ghost** [comment]
Yes, this is in order to edit them ; that why I asking for it into admin part. How can I delete a specific item ? Ho can I modify it ?
