### ISSUE TITLE
Table 'ls.cms_routes_access' doesn't exist

### ISSUE THREAD

**Issue by LoneFoxx** [Mathew78540/realaion#26]
Table 'ls.cms_routes_access' doesn't exist

Pls upload sql files for DataBase

and add in Root folder : vendor - else 
`C:\xampp\htdocs\1>php artisan migrate
PHP Warning:  require(C:\xampp\htdocs\1\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\1\bootstrap\autoload.php on line 17

Warning: require(C:\xampp\htdocs\1\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\1\bootstrap\autoload.php on line 17
PHP Fatal error:  require(): Failed opening required 'C:\xampp\htdocs\1\bootstrap/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\1\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\1\bootstrap/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\1\bootstrap\autoload.php on line 17`

**Comment by mathieuletyrant** [comment]
Hi,

No needs SQL. Just execute : `php artisan migrate`. And the website don't use table cms_routes_access.

And it's bad to push vendor folder. So you must install composer and execute : `composer install`
