### ISSUE TITLE
Missings Tables

### ISSUE THREAD

**Issue by ghost** [Mathew78540/realaion#3]
Hello,
Here are list of missing Database Tables : 

_QueryException in Connection.php line 624:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'aion_gs.ladder_player' doesn't exist (SQL: select \* from ladder_player order by rating desc limit 5)_

_QueryException in Connection.php line 624:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'aion_ws.config_slider' doesn't exist (SQL: select \* from `config_slider`)_

**Comment by mathieuletyrant** [comment]
Hi,

This is the SQL :

``` sql
CREATE TABLE `ladder_player` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `rank` int(11) DEFAULT NULL,
  `rating` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by AymenOthmani** [comment]
nous avons besoin de la table config_slider s'il vous plaît ajouter

**Comment by mathieuletyrant** [comment]
A executer dans la DB du site

``` sql
CREATE TABLE `config_slider` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) DEFAULT NULL,
  `path` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by AymenOthmani** [comment]
je besoin aussi autre table account_level  !! vous remercie pour la réponse :)

**Comment by mathieuletyrant** [comment]
Ls Database :

``` sql
CREATE TABLE `account_level` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `account_id` int(11) DEFAULT NULL,
  `total` int(11) DEFAULT NULL,
  `level` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by AymenOthmani** [comment]
i créé toutes les tables sql mais voici le résultat "  http://74.208.230.63/aion/public/ "
problème est de quoi? php version?

vous pouvez vous connecter avec le compte id luffy pw luffy

**Comment by mathieuletyrant** [comment]
Hi,

You must compile CSS and JS. For that you must have NodeJS install and after execute :

``` shell
npm i
npm i -g gulp
gulp script
gulp style
```

**Comment by mathieuletyrant** [comment]
If you need some help, you can contact me on Skype : Mathew78540

**Comment by ghost** [comment]
Please update procedure to complete the theme generating part if you solve his problem on Skype.

**Comment by ghost** [comment]
There is an error into main template.

In the file:

`resources/views/_layouts/master.blade.php`

Replace:

```
    <link href="/css/font-awesome.min.css" rel="stylesheet">
    <link href="/css/global.css" rel="stylesheet">
```

With:

```
    <link href="css/font-awesome.min.css" rel="stylesheet">
    <link href="css/global.css" rel="stylesheet">
```

EDIT : Hmm, may be there is something missing... URL rewrite rule ? Special Apache module ? I don't really understand where to launch the web site. Apache redirect should point on public folder ?

**Comment by mathieuletyrant** [comment]
You should point your Vhost on the public folder and if you are on apache, create a .htaccess files with this inside : 

```
Options +FollowSymLinks
RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]
```

**Comment by mathieuletyrant** [comment]
Check my last commit, maybe fix for assets link

**Comment by ghost** [comment]
The .htaccess is already into public folder.

I have updated apache config, now default root is on public folder, but when I click to any link (ie Team) it tries to go to page/team, and page/team does not exists (see screen shot)
![2016-07-28_22h49_23](https://cloud.githubusercontent.com/assets/20670942/17228940/8b117c6c-5515-11e6-9d8a-cf32f75b5a1b.png)
![2016-07-28_22h49_32](https://cloud.githubusercontent.com/assets/20670942/17228941/8b117d52-5515-11e6-837b-797801f7ca07.png)

**Comment by AymenOthmani** [comment]
for me everythinks working just i have problems in path ( links)
https://scontent-cdg2-1.xx.fbcdn.net/v/t35.0-12/13767360_1204056909638445_3315980957054269986_o.jpg?oh=4002d376a33a5e2a6531aaadee09ccc5&oe=579BF543
