### ISSUE TITLE
Shop : number of sales are not correctly updated

### ISSUE THREAD

**Issue by ghost** [Mathew78540/realaion#30]
If I check how many Epée d'Aile Ouragan are selled:
![2016-08-02_01h00_53](https://cloud.githubusercontent.com/assets/20670942/17311596/d045ac24-584c-11e6-9e77-ad976c86df15.png)
There is 14.

If I go to buy this item 2 times (in the shop, I click 2 times on cart button) and I buy 1 time 2 items:
![2016-08-02_01h01_17](https://cloud.githubusercontent.com/assets/20670942/17311621/fd42ea52-584c-11e6-9891-b79ef27193d1.png)

When I go back to Sales, it's incremented by only one, not two:
![2016-08-02_01h01_28](https://cloud.githubusercontent.com/assets/20670942/17311634/0fc7735a-584d-11e6-8fba-3b2d8328dfbf.png)

**Comment by mathieuletyrant** [comment]
For me it's normal, imagine you sell Kinah with a QT to 1.000.000.

**Comment by ghost** [comment]
Hmm I mean, fir Kinah if qty is 1.000.000 and player click 2 times to buy 2.000.000 kinah in one transaction, total sell should be +2 and it is currently +1

**Comment by mathieuletyrant** [comment]
Hum ok :)
