### ISSUE TITLE
cmd error

### ISSUE THREAD

**Issue by krokogames** [Mathew78540/realaion#31]
C:\wamp\www>php artisan migrate

---
-     Application In Production!     *
  **************************************

Do you really wish to run this command? [y/N] y
Migration table created successfully.

  [ErrorException]
  Missing argument 2 for Illuminate\Database\Schema\Builder::hasColumn(), called in C:\wamp\www\database\migrations\2
  016_07_29_122150_create_email.php on line 15 and defined

please help this problem thx.

**Comment by mathieuletyrant** [comment]
Fixes, please git pull the repo

**Comment by krokogames** [comment]
hm... Migrate work.

nex problem website not loading : https://ctrlv.cz/shots/2016/08/03/kOH1.png

full logs : http://pastebin.com/HkE3Ydd7

**Comment by mathieuletyrant** [comment]
I looked and find nothing ... Very strange. Have you data in the table `news` in the database for the website ?

**Comment by krokogames** [comment]
https://ctrlv.cz/shots/2016/08/03/34RS.png    db aion_ws

https://ctrlv.cz/shots/2016/08/03/IEYQ.png db aion_ws.news Data

**Comment by mathieuletyrant** [comment]
Have you the last version of the website ?

**Comment by krokogames** [comment]
its work I create random account aion_ls id1 name password and web 100% loading

db aion_ws news table account_id my problem

**Comment by mathieuletyrant** [comment]
Ah yes,

**Comment by krokogames** [comment]
https://ctrlv.cz/shots/2016/08/03/wu91.png thx for help :)
