### ISSUE TITLE
Linux Debian

### ISSUE THREAD

**Issue by krokogames** [Mathew78540/realaion#33]
Hello I need help with the installation site on my Debian linux.

Photo problem : https://ctrlv.cz/shots/2016/08/04/bMqa.png 

storage logs empty

**Comment by ghost** [comment]
Follow instructions correctly.
You need to replace AllowOverride None of your directly by AllowOverride All
In you env file, enable debug mode

**Comment by mathieuletyrant** [comment]
On debian, try : 

``` shell
chmod 777 -R storage
```

And don't missing : 

``` shell
composer install
php artisan migrate
php artisan db:seed
```

**Comment by krokogames** [comment]
hm... chmod -777 -R storage complete

composer install and more complete

Debug mode enable

website not loading :/

**Comment by mathieuletyrant** [comment]
Have you more information ? logs in storage

**Comment by krokogames** [comment]
its okey i set chmod 777 -R /var/www and work look http://185.91.116.159

**Comment by mathieuletyrant** [comment]
Strange, but cool if it's works 👍

**Comment by krokogames** [comment]
That's how my administration look or wrong for me     : https://ctrlv.cz/shots/2016/08/05/mz4L.png

**Comment by mathieuletyrant** [comment]
Can you open the console Chrome, and look errors in console ?

**Comment by krokogames** [comment]
https://ctrlv.cz/shots/2016/08/05/FV3K.png

**Comment by mathieuletyrant** [comment]
Fixes on the last commit, please `git pull` and test.

**Comment by krokogames** [comment]
Okey work thx for help Nice support :3
https://ctrlv.cz/shots/2016/08/05/Sb5T.png

**Comment by mathieuletyrant** [comment]
No-problem. Good luck. And if you have sommes issues or suggestion. Create a Issue on github.
