### ISSUE TITLE
Add Remove cache functionnality

### ISSUE THREAD

**Issue by ghost** [Mathew78540/realaion#34]
For some reason, I have to delete some "forever" cache, but if I try to remove the file I have a 404.
Is it possible to add a functionnality to remove all cache ? With some options, like checkbox for normal cache, forever cache, etc.

**Comment by mathieuletyrant** [comment]
And why you delete some cache ?

**Comment by ghost** [comment]
As Mathew explain me off Git, let use this command at root of website:

`php artisan cache:clear`

And it will remove all cache files.
