### ISSUE TITLE
install to ubuntu 14.04 LTS Server

### ISSUE THREAD

**Issue by LoneFoxx** [Mathew78540/realaion#35]
When i open site in WEB...this logs and message Whoops, looks like something went wrong.
`[2016-08-05 13:44:15] production.ERROR: exception 'PDOException' with message 'could not find driver' in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:55
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(55): PDO->__construct('mysql:host=93.1...', 'root', 'qwerty', Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(22): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=93.1...', Array, Array)
#2 /var/www/html/bootstrap/cache/compiled.php(11468): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 /var/www/html/bootstrap/cache/compiled.php(11464): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#4 /var/www/html/bootstrap/cache/compiled.php(11379): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'gameserver')
#5 /var/www/html/bootstrap/cache/compiled.php(11334): Illuminate\Database\DatabaseManager->makeConnection('gameserver')
#6 /var/www/html/bootstrap/cache/compiled.php(11205): Illuminate\Database\DatabaseManager->connection('gameserver')
#7 /var/www/html/bootstrap/cache/compiled.php(11192): Illuminate\Database\Eloquent\Model::resolveConnection('gameserver')
#8 /var/www/html/vendor/watson/rememberable/src/Rememberable.php(15): Illuminate\Database\Eloquent\Model->getConnection()
#9 /var/www/html/bootstrap/cache/compiled.php(10614): App\Models\Gameserver\Player->newBaseQueryBuilder()
#10 /var/www/html/bootstrap/cache/compiled.php(10604): Illuminate\Database\Eloquent\Model->newQueryWithoutScopes()
#11 /var/www/html/bootstrap/cache/compiled.php(11295): Illuminate\Database\Eloquent\Model->newQuery()
#12 [internal function]: Illuminate\Database\Eloquent\Model->__call('online', Array)
#13 [internal function]: App\Models\Gameserver\Player->online()
#14 /var/www/html/bootstrap/cache/compiled.php(11301): call_user_func_array(Array, Array)
#15 /var/www/html/app/Http/Controllers/Controller.php(49): Illuminate\Database\Eloquent\Model::__callStatic('online', Array)
#16 /var/www/html/app/Http/Controllers/Controller.php(49): App\Models\Gameserver\Player::online()
#17 /var/www/html/app/Http/Controllers/Controller.php(37): App\Http\Controllers\Controller->countPlayersOnline()
#18 [internal function]: App\Http\Controllers\Controller->__construct()
#19 /var/www/html/bootstrap/cache/compiled.php(1306): ReflectionClass->newInstanceArgs(Array)
#20 /var/www/html/bootstrap/cache/compiled.php(1242): Illuminate\Container\Container->build('App\Http\Contro...', Array)
#21 /var/www/html/bootstrap/cache/compiled.php(1783): Illuminate\Container\Container->make('App\Http\Contro...', Array)
#22 /var/www/html/bootstrap/cache/compiled.php(8964): Illuminate\Foundation\Application->make('App\Http\Contro...')
#23 /var/www/html/bootstrap/cache/compiled.php(8953): Illuminate\Routing\ControllerDispatcher->makeController('App\Http\Contro...')
#24 /var/www/html/bootstrap/cache/compiled.php(7906): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'index')
#25 /var/www/html/bootstrap/cache/compiled.php(7877): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#26 /var/www/html/bootstrap/cache/compiled.php(7530): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Routing\Router->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#28 /var/www/html/bootstrap/cache/compiled.php(9642): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#30 /var/www/html/bootstrap/cache/compiled.php(9624): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 /var/www/html/bootstrap/cache/compiled.php(7531): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#32 /var/www/html/bootstrap/cache/compiled.php(7519): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#33 /var/www/html/bootstrap/cache/compiled.php(7504): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#34 /var/www/html/bootstrap/cache/compiled.php(2310): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#35 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http{closure}(Object(Illuminate\Http\Request))
#36 /var/www/html/bootstrap/cache/compiled.php(9642): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 /var/www/html/app/Http/Middleware/HasVote.php(45): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: App\Http\Middleware\HasVote->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/html/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#40 /var/www/html/app/Http/Middleware/Language.php(32): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: App\Http\Middleware\Language->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/html/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#43 /var/www/html/bootstrap/cache/compiled.php(2925): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#44 /var/www/html/app/Http/Middleware/VerifyCsrfToken.php(23): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 [internal function]: App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/html/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#47 /var/www/html/bootstrap/cache/compiled.php(12993): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /var/www/html/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#50 /var/www/html/bootstrap/cache/compiled.php(11585): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#51 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /var/www/html/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#53 /var/www/html/bootstrap/cache/compiled.php(12730): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#54 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /var/www/html/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#56 /var/www/html/bootstrap/cache/compiled.php(12667): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /var/www/html/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#59 /var/www/html/bootstrap/cache/compiled.php(2982): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#60 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /var/www/html/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#62 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#63 /var/www/html/bootstrap/cache/compiled.php(9624): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#64 /var/www/html/bootstrap/cache/compiled.php(2257): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#65 /var/www/html/bootstrap/cache/compiled.php(2240): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#66 /var/www/html/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#67 {main}`

**Comment by mathieuletyrant** [comment]
What version of PHP you use ? Have you PDO ?

**Comment by LoneFoxx** [comment]
pls close) i foget install apt-get install php5-mysql
