### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ghost** [Mathew78540/realaion#4]
Use more neutral terms into Web site:
- DB_DATABASE_GS = aion_gs instead of real_gs
- DB_DATABASE_LS  = aion_ls instead of real_ls
- DB_DATABASE_WS  = aion_ws instead of real_ws
- Default images (background, logo, etc.) without Real
- Using Toll term instead of Real's
- Change column name of table used for storage toll points (currently real) and update code that call this column
- Use default email adress withour real-aion domain

**Comment by mathieuletyrant** [comment]
I'm agree,

But for change term real to toll, i think not. 
Why ? Because if the user buy toll on the website and the user is connect In-game you will have conflicts. 
This is why i use other table. And you must create command inGame who transfert shop points to toll.

**Comment by ghost** [comment]
Yes I propose Toll but the main idea is to replace real by something more "neutral"

**Comment by mathieuletyrant** [comment]
Yes i starting to rename `reals` to `shop_points`
