### ISSUE TITLE
Next to #20 : Add option to display table with all items

### ISSUE THREAD

**Issue by ghost** [Mathew78540/realaion#43]
For the moment, if I want to see all items I created in shop, I must on top select Item + add a "%" in search zone + Enter on keyboard (no button).
![2016-08-17_23h54_47](https://cloud.githubusercontent.com/assets/20670942/17754780/795e7102-64d6-11e6-94db-ffe07a2f233b.png)
Is it possible to add a specific function that will display all shop items, with some filters ? For example, you can add [Datatable for JQuery](https://datatables.net/)

**Comment by mathieuletyrant** [comment]
Not a priority for now.
