### ISSUE TITLE
Request : Create item add option : Enable preview command Yes/No (default Yes)

### ISSUE THREAD

**Issue by ghost** [Mathew78540/realaion#44]
It does not make sense into the shop to display the preview button for some items:
![2016-08-21_00h42_58](https://cloud.githubusercontent.com/assets/20670942/17834265/4a2fc05c-6738-11e6-8809-7b0af54dbf73.png)
There is no preview for this item, so it's not necessary to show button Preview, so could you add an option into Add item that will allow display of preview button or not.

**Comment by mathieuletyrant** [comment]
Please, execute : `php artisan migrate` before.
