### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by BieeeLC** [Mathew78540/realaion#46]
How do I resolve these errors? :C

[http://image.prntscr.com/image/daec4af06a574a2dbb277c2d595bb52e.jpg](url)
[http://image.prntscr.com/image/f4c99173b3b249d7a0bed1f37b957696.jpg](url)
[http://image.prntscr.com/image/af439976f77f4179b0864f1bfb7b1a85.jpg](url)

**Comment by mathieuletyrant** [comment]
It's because there are a basic news link to account with ID(1), so create your first account.

**Comment by BieeeLC** [comment]
I did not understand what you mean, you can use other words?

**Comment by ghost** [comment]
Create one account into the web site
You need one account for site works correctly.
Go to Register (or S'enregistrer) and complete the form :)

**Comment by BieeeLC** [comment]
Reseted entire database, I created an account on the website and still not working.
[http://image.prntscr.com/image/8bf29fc42dfe49e7b34464c2104c5b38.jpg](url)

**Comment by mathieuletyrant** [comment]
Please set the account ID to 1

**Comment by ghost** [comment]
So bad, these news are looking for account ID 1 in your database :D 
Try to change your account id by 1, else empty it with a Truncate action (that will reset your auto increment IDs)

**Comment by BieeeLC** [comment]
t worked perfectly, just change the ID to 1, how do I make my administrator account?

**Comment by mathieuletyrant** [comment]
1. Change your access_level to 2 (minimum value)
2. Login
3. In the footer there is a link 'Administration'

You can change the minimum access_level in `config/aion.php`
