### ISSUE TITLE
webshop 

### ISSUE THREAD

**Issue by AymenOthmani** [Mathew78540/realaion#7]
- Presque tout fonctionne bien, mais quand j'ajouter des articles à la boutique je ne peux pas le voir dans la boutique et n'existe pas dans la table de base de données.
- Essayé d'ajouter items a la base de données, ont travaillé, mais les éléments d'icônes et les statistiques ne show pas and quand clic dans sous-catégories i a la page vide

**Comment by mathieuletyrant** [comment]
I test, and create a category / create a sub category / create item works fine. It's you sorry.

**Comment by AymenOthmani** [comment]
aucun problème je peux ajouter de la base de données, mais l'icône items ne sont pas travailler :ghost: 

https://scontent-cdg2-1.xx.fbcdn.net/v/t35.0-12/13641119_1204596059584530_4498105821445894005_o.jpg?oh=1c27d224edb47905f65f06d82ab10d82&oe=579E75A4

**Comment by mathieuletyrant** [comment]
Can i have item_id ?

**Comment by AymenOthmani** [comment]
http://aiondatabase.net/us/item/186000247/

id : 186000247

**Comment by mathieuletyrant** [comment]
Works fine : https://infinit.io/_/39uWr3d
Look your console and look if you have an error

**Comment by AymenOthmani** [comment]
yea error about links xD need use like this Syntaxe "{!! asset('images/logo.png') !!}"

did you know haw i can fix it ?

https://scontent-cdg2-1.xx.fbcdn.net/v/t35.0-12/13838103_1204612489582887_45709155_o.png?oh=7aace0673490172a04d5d5811c53e61b&oe=579D7CFB

**Comment by mathieuletyrant** [comment]
I can't it's a Ajax call. 
For fix the problem, you must create a domain and point to public folder.

**Comment by AymenOthmani** [comment]
ok thanks a lot man, good luck in your work

**Comment by mathieuletyrant** [comment]
No problem, I close the issue
