### ISSUE TITLE
php artisan migrate : duplicate errors

### ISSUE THREAD

**Issue by ghost** [Mathew78540/realaion#8]
I have duplicate errors when I launch php artisan migrate (and the next one):

```
  [Illuminate\Database\QueryException]
  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'email' (SQL: alter table `account_data` add `email` varchar(255) not null)
```

Is it possible here to add a check like only if column does not exist try to create it, or if it already exists, prompt : Do you want to delete it ? y/n

**Comment by mathieuletyrant** [comment]
Yes, of course, i will do that tomorrow.
